### ISSUE TITLE
History Tab

### ISSUE THREAD

**Issue by joshhacksthings** [alexangom/iOS_final_project#2]
Click "History" tab from any view controller.
Immediately met with an error:
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier activityEntry - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'`

Followed first two links which seemed promising but did not help:
[see here](https://stackoverflow.com/questions/11221802/nib-but-didnt-get-a-uitableview)

**Comment by alexangom** [comment]
Was this resolved?

**Comment by joshhacksthings** [comment]
I have not yet resolved it. If you have resolved ir, you can mark the thread as resolved

**Comment by joshhacksthings** [comment]
Resolved with last Josh2 push to master.
